=== FelanNemo/JSK2017/Stuff/gemliste_knz/authstrukturdaten.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.help.gv.at/xml/strukturdaten/#20060626" targetNamespace="http://www.help.gv.at/xml/strukturdaten/#20060626">
	<element name="strukturdaten" type="tns:StrukturdatenType"/>
	<complexType name="StrukturdatenType">
		<choice>
			<element name="metadaten" type="tns:MetaDatenType" maxOccurs="unbounded"/>
			<element name="daten" type="tns:DatenType"/>
		</choice>
	</complexType>
	<complexType name="MetaDatenType">
		<sequence>
			<element name="letzteaenderung" type="dateTime"/>
			<element name="datenstruktur" type="tns:DatenstrukturType"/>
		</sequence>
		<attribute name="datenname" type="string" use="required"/>
		<attribute name="datenuri" type="anyURI" use="required"/>
	</complexType>
	<complexType name="DatenstrukturType">
		<sequence maxOccurs="unbounded" minOccurs="1">
			<element name="elementname">
				<complexType>
					<simpleContent>
						<extension base="string">
							<attribute name="datatype" type="string" use="required"/>
						</extension>
					</simpleContent>
				</complexType>
			</element>
		</sequence>
	</complexType>
	<complexType name="DatenType">
		<sequence>
			<element name="datensatz" maxOccurs="unbounded" minOccurs="0">
				<complexType>
					<sequence maxOccurs="unbounded" minOccurs="1">
						<element name="element" type="string"/>
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>
</schema>

=== FelanNemo/JSK2017/d7-2017-03-08/plz/gemliste_knz/gemliste_knz_status.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:strukturdaten xmlns:tns="http://www.help.gv.at/xml/strukturdaten/#20060626" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.help.gv.at/xml/strukturdaten/#20060626 authstrukturdaten.xsd ">
<metadaten datenname="VERZEICHNIS" datenuri="http://www.statistik.at/web_de/statistiken/regionales/regionale_gliederungen/gemliste_knz.xml">
<letzteaenderung>2016-10-20T14:01:32</letzteaenderung>
<datenstruktur>
	<elementname datatype="CHAR(5)">GEMNR</elementname>
	<elementname datatype="VARCHAR(50)">GEMNAM38</elementname>
	<elementname datatype="CHAR(5)">GEMNR2</elementname>
	<elementname datatype="CHAR(2)">GEMST</elementname>
	<elementname datatype="CHAR(4)">GEMPLZ</elementname>
	<elementname datatype="CHAR(4)*">PLZ</elementname>

</datenstruktur>
</metadaten>
</tns:strukturdaten>
